In [2]:
import numpy as np
from inflammation.models import daily_mean, daily_max, daily_min

In [4]:
data = np.loadtxt('data/inflammation-01.csv', delimiter=',')
print(data)
print(data.shape)


[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
(60, 40)


In [11]:
print(daily_mean(data))
print(daily_mean(data).shape)
print(daily_max(data))
print(daily_max(data).shape)
print(daily_min(data))
print(daily_min(data).shape)

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]
(40,)
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 19. 18. 17. 16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.
  4.  3.  2.  1.]
(40,)
[0. 0. 0. 0. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3. 4. 5. 5. 5. 5. 4. 4. 4.
 4. 3. 3. 3. 3. 2. 2. 2. 2. 1. 1. 1. 1. 0. 0. 0.]
(40,)


In [16]:
array = np.array([[1,2], [3,4], [5,6]])
print(np.mean(array, axis=0))
print(np.mean(array, axis=1))
print(np.mean(array))

[3. 4.]
[1.5 3.5 5.5]
3.5


In [21]:
import numpy.testing as npt
npt.assert_array_equal(daily_mean(data), np.mean(data, axis=0))
test_input = array
test_result = [3, 4]
npt.assert_array_equal(daily_mean(test_input), test_result)


In [26]:
def test_daily_mean_integers():
    test_input = array
    test_result = [3, 4]
    npt.assert_array_equal(daily_mean(test_input), test_result)

def test_daily_mean_zeros():
    test_input = np.zeros((3, 2))
    test_result = np.zeros(2)
    npt.assert_array_equal(daily_mean(test_input), test_result)

test_daily_mean_integers()
test_daily_mean_zeros()

In [ ]:
import pytest

